{
  "id": "ALSA-2023:0833",
  "summary": "Moderate: python3 security update",
  "affected": [
    {
      "package": {
        "ecosystem": "AlmaLinux:8",
        "name": "platform-python"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "3.6.8-48.el8_7.1.alma"
            }
          ]
        }
      ]
    },
    {
      "package": {
        "ecosystem": "AlmaLinux:8",
        "name": "platform-python-debug"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "3.6.8-48.el8_7.1.alma"
            }
          ]
        }
      ]
    },
    {
      "package": {
        "ecosystem": "AlmaLinux:8",
        "name": "platform-python-devel"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "3.6.8-48.el8_7.1.alma"
            }
          ]
        }
      ]
    },
    {
      "package": {
        "ecosystem": "AlmaLinux:8",
        "name": "python3-idle"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "3.6.8-48.el8_7.1.alma"
            }
          ]
        }
      ]
    },
    {
      "package": {
        "ecosystem": "AlmaLinux:8",
        "name": "python3-libs"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "3.6.8-48.el8_7.1.alma"
            }
          ]
        }
      ]
    },
    {
      "package": {
        "ecosystem": "AlmaLinux:8",
        "name": "python3-test"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "3.6.8-48.el8_7.1.alma"
            }
          ]
        }
      ]
    },
    {
      "package": {
        "ecosystem": "AlmaLinux:8",
        "name": "python3-tkinter"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "3.6.8-48.el8_7.1.alma"
            }
          ]
        }
      ]
    }
  ],
  "aliases": [
    "CVE-2020-10735",
    "CVE-2021-28861",
    "CVE-2022-45061"
  ],
  "published": "2023-02-21T00:00:00Z",
  "modified": "2023-03-13T16:37:05Z",
  "details": "Python is an interpreted, interactive, object-oriented programming language, which includes modules, classes, exceptions, very high level dynamic data types and dynamic typing. Python supports interfaces to many system calls and libraries, as well as to various windowing systems.\n\nSecurity Fix(es):\n\n* python: int() type in PyLong_FromString() does not limit amount of digits converting text to int leading to DoS (CVE-2020-10735)\n* python: open redirection vulnerability in lib/http/server.py may lead to information disclosure (CVE-2021-28861)\n* Python: CPU denial of service via inefficient IDNA decoder (CVE-2022-45061)\n\nFor more details about the security issue(s), including the impact, a CVSS score, acknowledgments, and other related information, refer to the CVE page(s) listed in the References section.",
  "references": [
    {
      "url": "https://access.redhat.com/errata/RHSA-2023:0833",
      "type": "ADVISORY"
    },
    {
      "url": "https://access.redhat.com/security/cve/CVE-2020-10735",
      "type": "REPORT"
    },
    {
      "url": "https://access.redhat.com/security/cve/CVE-2021-28861",
      "type": "REPORT"
    },
    {
      "url": "https://access.redhat.com/security/cve/CVE-2022-45061",
      "type": "REPORT"
    },
    {
      "url": "https://bugzilla.redhat.com/1834423",
      "type": "REPORT"
    },
    {
      "url": "https://bugzilla.redhat.com/2120642",
      "type": "REPORT"
    },
    {
      "url": "https://bugzilla.redhat.com/2144072",
      "type": "REPORT"
    },
    {
      "url": "https://errata.almalinux.org/8/ALSA-2023-0833.html",
      "type": "ADVISORY"
    }
  ]
}