{
  "id": "ALSA-2024:6962",
  "summary": "Moderate: python3.11 security update",
  "affected": [
    {
      "package": {
        "ecosystem": "AlmaLinux:8",
        "name": "python3.11"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "3.11.9-7.el8_10"
            }
          ]
        }
      ]
    },
    {
      "package": {
        "ecosystem": "AlmaLinux:8",
        "name": "python3.11-debug"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "3.11.9-7.el8_10"
            }
          ]
        }
      ]
    },
    {
      "package": {
        "ecosystem": "AlmaLinux:8",
        "name": "python3.11-devel"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "3.11.9-7.el8_10"
            }
          ]
        }
      ]
    },
    {
      "package": {
        "ecosystem": "AlmaLinux:8",
        "name": "python3.11-idle"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "3.11.9-7.el8_10"
            }
          ]
        }
      ]
    },
    {
      "package": {
        "ecosystem": "AlmaLinux:8",
        "name": "python3.11-libs"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "3.11.9-7.el8_10"
            }
          ]
        }
      ]
    },
    {
      "package": {
        "ecosystem": "AlmaLinux:8",
        "name": "python3.11-rpm-macros"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "3.11.9-7.el8_10"
            }
          ]
        }
      ]
    },
    {
      "package": {
        "ecosystem": "AlmaLinux:8",
        "name": "python3.11-test"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "3.11.9-7.el8_10"
            }
          ]
        }
      ]
    },
    {
      "package": {
        "ecosystem": "AlmaLinux:8",
        "name": "python3.11-tkinter"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "3.11.9-7.el8_10"
            }
          ]
        }
      ]
    }
  ],
  "related": [
    "CVE-2024-4032",
    "CVE-2024-6923",
    "CVE-2024-8088"
  ],
  "published": "2024-09-24T00:00:00Z",
  "modified": "2024-09-24T09:21:42Z",
  "details": "Python is an interpreted, interactive, object-oriented programming language, which includes modules, classes, exceptions, very high level dynamic data types and dynamic typing. Python supports interfaces to many system calls and libraries, as well as to various windowing systems.\n\nSecurity Fix(es):\n\n* python: incorrect IPv4 and IPv6 private ranges (CVE-2024-4032)\n* cpython: python: email module doesn't properly quotes newlines in email headers, allowing header injection (CVE-2024-6923)\n* python: cpython: From NVD collector (CVE-2024-8088)\n\nFor more details about the security issue(s), including the impact, a CVSS score, acknowledgments, and other related information, refer to the CVE page(s) listed in the References section.",
  "references": [
    {
      "url": "https://access.redhat.com/errata/RHSA-2024:6962",
      "type": "ADVISORY"
    },
    {
      "url": "https://access.redhat.com/security/cve/CVE-2024-4032",
      "type": "REPORT"
    },
    {
      "url": "https://access.redhat.com/security/cve/CVE-2024-6923",
      "type": "REPORT"
    },
    {
      "url": "https://access.redhat.com/security/cve/CVE-2024-8088",
      "type": "REPORT"
    },
    {
      "url": "https://bugzilla.redhat.com/2292921",
      "type": "REPORT"
    },
    {
      "url": "https://bugzilla.redhat.com/2302255",
      "type": "REPORT"
    },
    {
      "url": "https://bugzilla.redhat.com/2307370",
      "type": "REPORT"
    },
    {
      "url": "https://errata.almalinux.org/8/ALSA-2024-6962.html",
      "type": "ADVISORY"
    }
  ]
}