{
  "id": "ALSA-2023:0952",
  "summary": "Moderate: python-setuptools security update",
  "affected": [
    {
      "package": {
        "ecosystem": "AlmaLinux:9",
        "name": "python3-setuptools"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "53.0.0-10.el9_1.1"
            }
          ]
        }
      ]
    },
    {
      "package": {
        "ecosystem": "AlmaLinux:9",
        "name": "python3-setuptools-wheel"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "53.0.0-10.el9_1.1"
            }
          ]
        }
      ]
    }
  ],
  "aliases": [
    "CVE-2022-40897"
  ],
  "published": "2023-02-28T00:00:00Z",
  "modified": "2023-02-28T17:39:56Z",
  "details": "The python-setuptools package provides a collection of enhancements to Python distribution utilities allowing convenient building and distribution of Python packages.\n\nSecurity Fix(es):\n\n* pypa-setuptools: Regular Expression Denial of Service (ReDoS) in package_index.py (CVE-2022-40897)\n\nFor more details about the security issue(s), including the impact, a CVSS score, acknowledgments, and other related information, refer to the CVE page(s) listed in the References section.",
  "references": [
    {
      "url": "https://access.redhat.com/errata/RHSA-2023:0952",
      "type": "ADVISORY"
    },
    {
      "url": "https://access.redhat.com/security/cve/CVE-2022-40897",
      "type": "REPORT"
    },
    {
      "url": "https://bugzilla.redhat.com/2158559",
      "type": "REPORT"
    },
    {
      "url": "https://errata.almalinux.org/9/ALSA-2023-0952.html",
      "type": "ADVISORY"
    }
  ]
}